# Generated by Django 5.0.5 on 2024-05-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_data',
            new_name='created_data',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
